spring:
  application.name: task
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
flyway:
  user: user
  password:
  schemas: app-db
  url: jdbc:h2:mem:mydb
  locations: filesystem:db/migration